import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  row: {
    backgroundColor: 'white',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    margin: 15,
  },
  subview: {
    flex: 1,
    justifyContent: 'center',
    width:'90%',
  },
  textBox: {
    backgroundColor: '#F4F5F4',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    marginTop: 10,
    marginBottom: 10,
  },
  submitButton: {
    backgroundColor: '#3297C1',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    marginTop: 10,
    marginBottom: 10,
  },
  toggleButtonInactive: {
    backgroundColor: '#fff',
    borderColor: '#E2E5E6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    borderWidth: 2,
    margin: 5,
    elevation: 3,
    marginTop: 10,
    marginBottom: 10,
  },
  toggleButtonActive: {
    backgroundColor: '#A6DDF4',
    borderColor: '#E2E5E6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    borderWidth: 2,
    margin: 5,
    elevation: 3,
    marginTop: 10,
    marginBottom: 10,
  },
  buttonText: {
    justifyContent: 'center',
    fontSize: 16,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },
  heading: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
  },
  subheading: {
    fontSize: 15,
    color: '#737B7D',
  },
  dropdownRow: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  dropdown: {
    backgroundColor: "#F4F5F4",
    borderWidth: 0,
  },
  dropdownContainer: {
    backgroundColor: "#F4F5F4",
    // width: '50%',
    flex: 1,
    margin: 5
  }
});
